apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/sns.services.k8s.aws_platformapplications.yaml
  - bases/sns.services.k8s.aws_platformendpoints.yaml
  - bases/sns.services.k8s.aws_topics.yaml
